name: Fetch API
        on:
      schedule:
        - cron: "*/5 * * * *" # Every 5 minutes
    jobs:
      refresh-feed:
        runs-on: ubuntu-latest
        steps:
          - name: Fetch API Data
            uses: JamesIves/fetch-api-data-action@releases/v1
            with:
              ENDPOINT: https://potion-api.vercel.app/table?id=fe3fe0e8c9e54061b7412307da4c035f
              # your api URL 
              SAVE_LOCATION: ./socials.json
              # folder for svelte + svelte spa router 
              BRANCH: master # Pushes the updates to the master branch.


          - name: Update resources
            uses: test-room-7/action-update-file@v1
            with:
              file-path: ./socials.json
              commit-msg: Updated data 
              github-token: ${{ secrets.TOKEN }}



# name: "Recent Activity Updater Bot"

# on:
#   push:
#     branches:
#       - master
#   schedule:
#     - cron: "*/5 * * * *" # Every 5 minutes

# jobs:
#   bot:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1

#     - name: "Install Node"
#       uses: actions/setup-node@v1
#       with:
#         node-version: '15.x'

#     - name: "Install NPM dependancies"
#       run: npm install

#     - name: "Run code"
#       run: node index.js